language: generic
sudo : required

services: 
  - docker

before_install: 
  - docker build -t amirsha99/react_pro -f Dockerfile.dev .

script: 
  - docker run -e CI=true amirsha99/react_pro npm run test